/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as DailyLifeRouteImport } from './routes/daily-life'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityAskRouteImport } from './routes/community.ask'
import { Route as CommunityQQuestionIdRouteImport } from './routes/community.q.$questionId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyLifeRoute = DailyLifeRouteImport.update({
  id: '/daily-life',
  path: '/daily-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityAskRoute = CommunityAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityQQuestionIdRoute = CommunityQQuestionIdRouteImport.update({
  id: '/q/$questionId',
  path: '/q/$questionId',
  getParentRoute: () => CommunityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/daily-life': typeof DailyLifeRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/community/ask': typeof CommunityAskRoute
  '/community/': typeof CommunityIndexRoute
  '/community/q/$questionId': typeof CommunityQQuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/daily-life': typeof DailyLifeRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/community/ask': typeof CommunityAskRoute
  '/community': typeof CommunityIndexRoute
  '/community/q/$questionId': typeof CommunityQQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/daily-life': typeof DailyLifeRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/community/ask': typeof CommunityAskRoute
  '/community/': typeof CommunityIndexRoute
  '/community/q/$questionId': typeof CommunityQQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/daily-life'
    | '/guides'
    | '/login'
    | '/reviews'
    | '/signup'
    | '/community/ask'
    | '/community/'
    | '/community/q/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/daily-life'
    | '/guides'
    | '/login'
    | '/reviews'
    | '/signup'
    | '/community/ask'
    | '/community'
    | '/community/q/$questionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/daily-life'
    | '/guides'
    | '/login'
    | '/reviews'
    | '/signup'
    | '/community/ask'
    | '/community/'
    | '/community/q/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  ContactRoute: typeof ContactRoute
  DailyLifeRoute: typeof DailyLifeRoute
  GuidesRoute: typeof GuidesRoute
  LoginRoute: typeof LoginRoute
  ReviewsRoute: typeof ReviewsRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-life': {
      id: '/daily-life'
      path: '/daily-life'
      fullPath: '/daily-life'
      preLoaderRoute: typeof DailyLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/ask': {
      id: '/community/ask'
      path: '/ask'
      fullPath: '/community/ask'
      preLoaderRoute: typeof CommunityAskRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/q/$questionId': {
      id: '/community/q/$questionId'
      path: '/q/$questionId'
      fullPath: '/community/q/$questionId'
      preLoaderRoute: typeof CommunityQQuestionIdRouteImport
      parentRoute: typeof CommunityRoute
    }
  }
}

interface CommunityRouteChildren {
  CommunityAskRoute: typeof CommunityAskRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  CommunityQQuestionIdRoute: typeof CommunityQQuestionIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityAskRoute: CommunityAskRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  CommunityQQuestionIdRoute: CommunityQQuestionIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRouteWithChildren,
  ContactRoute: ContactRoute,
  DailyLifeRoute: DailyLifeRoute,
  GuidesRoute: GuidesRoute,
  LoginRoute: LoginRoute,
  ReviewsRoute: ReviewsRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
