/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PromptHiveRouteImport } from './routes/prompt-hive'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DailyLifeRouteImport } from './routes/daily-life'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromptHiveIndexRouteImport } from './routes/prompt-hive.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as PromptHiveSubmitRouteImport } from './routes/prompt-hive.submit'
import { Route as CommunityTopicsRouteImport } from './routes/community.topics'
import { Route as CommunityAskRouteImport } from './routes/community.ask'
import { Route as ApiLoginDotphpRouteImport } from './routes/api/login[.]php'
import { Route as CommunityUUsernameRouteImport } from './routes/community.u.$username'
import { Route as CommunityTopicsSlugRouteImport } from './routes/community.topics.$slug'
import { Route as CommunityQQuestionIdRouteImport } from './routes/community.q.$questionId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptHiveRoute = PromptHiveRouteImport.update({
  id: '/prompt-hive',
  path: '/prompt-hive',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyLifeRoute = DailyLifeRouteImport.update({
  id: '/daily-life',
  path: '/daily-life',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptHiveIndexRoute = PromptHiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PromptHiveRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const PromptHiveSubmitRoute = PromptHiveSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => PromptHiveRoute,
} as any)
const CommunityTopicsRoute = CommunityTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityAskRoute = CommunityAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => CommunityRoute,
} as any)
const ApiLoginDotphpRoute = ApiLoginDotphpRouteImport.update({
  id: '/api/login.php',
  path: '/api/login.php',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityUUsernameRoute = CommunityUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityTopicsSlugRoute = CommunityTopicsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CommunityTopicsRoute,
} as any)
const CommunityQQuestionIdRoute = CommunityQQuestionIdRouteImport.update({
  id: '/q/$questionId',
  path: '/q/$questionId',
  getParentRoute: () => CommunityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/daily-life': typeof DailyLifeRoute
  '/disclaimer': typeof DisclaimerRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/prompt-hive': typeof PromptHiveRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/login.php': typeof ApiLoginDotphpRoute
  '/community/ask': typeof CommunityAskRoute
  '/community/topics': typeof CommunityTopicsRouteWithChildren
  '/prompt-hive/submit': typeof PromptHiveSubmitRoute
  '/community/': typeof CommunityIndexRoute
  '/prompt-hive/': typeof PromptHiveIndexRoute
  '/community/q/$questionId': typeof CommunityQQuestionIdRoute
  '/community/topics/$slug': typeof CommunityTopicsSlugRoute
  '/community/u/$username': typeof CommunityUUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/daily-life': typeof DailyLifeRoute
  '/disclaimer': typeof DisclaimerRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/login.php': typeof ApiLoginDotphpRoute
  '/community/ask': typeof CommunityAskRoute
  '/community/topics': typeof CommunityTopicsRouteWithChildren
  '/prompt-hive/submit': typeof PromptHiveSubmitRoute
  '/community': typeof CommunityIndexRoute
  '/prompt-hive': typeof PromptHiveIndexRoute
  '/community/q/$questionId': typeof CommunityQQuestionIdRoute
  '/community/topics/$slug': typeof CommunityTopicsSlugRoute
  '/community/u/$username': typeof CommunityUUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/daily-life': typeof DailyLifeRoute
  '/disclaimer': typeof DisclaimerRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/prompt-hive': typeof PromptHiveRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/login.php': typeof ApiLoginDotphpRoute
  '/community/ask': typeof CommunityAskRoute
  '/community/topics': typeof CommunityTopicsRouteWithChildren
  '/prompt-hive/submit': typeof PromptHiveSubmitRoute
  '/community/': typeof CommunityIndexRoute
  '/prompt-hive/': typeof PromptHiveIndexRoute
  '/community/q/$questionId': typeof CommunityQQuestionIdRoute
  '/community/topics/$slug': typeof CommunityTopicsSlugRoute
  '/community/u/$username': typeof CommunityUUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/daily-life'
    | '/disclaimer'
    | '/guides'
    | '/login'
    | '/privacy'
    | '/prompt-hive'
    | '/reviews'
    | '/signup'
    | '/terms'
    | '/api/login.php'
    | '/community/ask'
    | '/community/topics'
    | '/prompt-hive/submit'
    | '/community/'
    | '/prompt-hive/'
    | '/community/q/$questionId'
    | '/community/topics/$slug'
    | '/community/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/daily-life'
    | '/disclaimer'
    | '/guides'
    | '/login'
    | '/privacy'
    | '/reviews'
    | '/signup'
    | '/terms'
    | '/api/login.php'
    | '/community/ask'
    | '/community/topics'
    | '/prompt-hive/submit'
    | '/community'
    | '/prompt-hive'
    | '/community/q/$questionId'
    | '/community/topics/$slug'
    | '/community/u/$username'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/daily-life'
    | '/disclaimer'
    | '/guides'
    | '/login'
    | '/privacy'
    | '/prompt-hive'
    | '/reviews'
    | '/signup'
    | '/terms'
    | '/api/login.php'
    | '/community/ask'
    | '/community/topics'
    | '/prompt-hive/submit'
    | '/community/'
    | '/prompt-hive/'
    | '/community/q/$questionId'
    | '/community/topics/$slug'
    | '/community/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DailyLifeRoute: typeof DailyLifeRoute
  DisclaimerRoute: typeof DisclaimerRoute
  GuidesRoute: typeof GuidesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  PromptHiveRoute: typeof PromptHiveRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiLoginDotphpRoute: typeof ApiLoginDotphpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-hive': {
      id: '/prompt-hive'
      path: '/prompt-hive'
      fullPath: '/prompt-hive'
      preLoaderRoute: typeof PromptHiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-life': {
      id: '/daily-life'
      path: '/daily-life'
      fullPath: '/daily-life'
      preLoaderRoute: typeof DailyLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-hive/': {
      id: '/prompt-hive/'
      path: '/'
      fullPath: '/prompt-hive/'
      preLoaderRoute: typeof PromptHiveIndexRouteImport
      parentRoute: typeof PromptHiveRoute
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/prompt-hive/submit': {
      id: '/prompt-hive/submit'
      path: '/submit'
      fullPath: '/prompt-hive/submit'
      preLoaderRoute: typeof PromptHiveSubmitRouteImport
      parentRoute: typeof PromptHiveRoute
    }
    '/community/topics': {
      id: '/community/topics'
      path: '/topics'
      fullPath: '/community/topics'
      preLoaderRoute: typeof CommunityTopicsRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/ask': {
      id: '/community/ask'
      path: '/ask'
      fullPath: '/community/ask'
      preLoaderRoute: typeof CommunityAskRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/api/login.php': {
      id: '/api/login.php'
      path: '/api/login.php'
      fullPath: '/api/login.php'
      preLoaderRoute: typeof ApiLoginDotphpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/u/$username': {
      id: '/community/u/$username'
      path: '/u/$username'
      fullPath: '/community/u/$username'
      preLoaderRoute: typeof CommunityUUsernameRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/topics/$slug': {
      id: '/community/topics/$slug'
      path: '/$slug'
      fullPath: '/community/topics/$slug'
      preLoaderRoute: typeof CommunityTopicsSlugRouteImport
      parentRoute: typeof CommunityTopicsRoute
    }
    '/community/q/$questionId': {
      id: '/community/q/$questionId'
      path: '/q/$questionId'
      fullPath: '/community/q/$questionId'
      preLoaderRoute: typeof CommunityQQuestionIdRouteImport
      parentRoute: typeof CommunityRoute
    }
  }
}

interface CommunityTopicsRouteChildren {
  CommunityTopicsSlugRoute: typeof CommunityTopicsSlugRoute
}

const CommunityTopicsRouteChildren: CommunityTopicsRouteChildren = {
  CommunityTopicsSlugRoute: CommunityTopicsSlugRoute,
}

const CommunityTopicsRouteWithChildren = CommunityTopicsRoute._addFileChildren(
  CommunityTopicsRouteChildren,
)

interface CommunityRouteChildren {
  CommunityAskRoute: typeof CommunityAskRoute
  CommunityTopicsRoute: typeof CommunityTopicsRouteWithChildren
  CommunityIndexRoute: typeof CommunityIndexRoute
  CommunityQQuestionIdRoute: typeof CommunityQQuestionIdRoute
  CommunityUUsernameRoute: typeof CommunityUUsernameRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityAskRoute: CommunityAskRoute,
  CommunityTopicsRoute: CommunityTopicsRouteWithChildren,
  CommunityIndexRoute: CommunityIndexRoute,
  CommunityQQuestionIdRoute: CommunityQQuestionIdRoute,
  CommunityUUsernameRoute: CommunityUUsernameRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface PromptHiveRouteChildren {
  PromptHiveSubmitRoute: typeof PromptHiveSubmitRoute
  PromptHiveIndexRoute: typeof PromptHiveIndexRoute
}

const PromptHiveRouteChildren: PromptHiveRouteChildren = {
  PromptHiveSubmitRoute: PromptHiveSubmitRoute,
  PromptHiveIndexRoute: PromptHiveIndexRoute,
}

const PromptHiveRouteWithChildren = PromptHiveRoute._addFileChildren(
  PromptHiveRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DailyLifeRoute: DailyLifeRoute,
  DisclaimerRoute: DisclaimerRoute,
  GuidesRoute: GuidesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  PromptHiveRoute: PromptHiveRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiLoginDotphpRoute: ApiLoginDotphpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
